{
 "title": "tracker_dcs_testdb",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Channel",
    "query": "SHOW TAG VALUES ON \"testdb\" FROM \"channels\" WITH KEY = \"id\""
   }
  ]
 },
 "panels": [
  {
   "title": "LV",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "$col  $tag_id ($tag_module)",
     "groupBy": [
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" }
     ],
     "measurement": "channels",
     "query": "SELECT LAST(\"V0Set\") FROM \"autogen\".\"hv\" WHERE (\"number\" = '0') AND $timeFilter",
     "select": [
      [
       { "params": [ "lv_setV" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$Channel$/" }
     ]
    },
    {
     "alias": "$col  $tag_id ($tag_module)",
     "groupBy": [
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" }
     ],
     "measurement": "channels",
     "query": "SELECT \"V0Set\" FROM \"testdb\".\"hv\" WHERE \"number\"='1' GROUP BY time(1s) fill(0)",
     "select": [
      [
       { "params": [ "lv_vMon" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$Channel$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "BME $tag_sensor",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "BME_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DS $tag_sensor",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "DS_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "BMI_humi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HV",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "$col  $tag_id ($tag_module)",
     "groupBy": [
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "id" ], "type": "tag" }
     ],
     "measurement": "channels",
     "query": "SELECT LAST(\"V0Set\") FROM \"autogen\".\"hv\" WHERE (\"number\" = '0') AND $timeFilter",
     "select": [
      [
       { "params": [ "hv_setV" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$Channel$/" }
     ]
    },
    {
     "alias": "$col  $tag_id ($tag_module)",
     "groupBy": [
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "id" ], "type": "tag" }
     ],
     "measurement": "channels",
     "query": "SELECT \"V0Set\" FROM \"testdb\".\"hv\" WHERE \"number\"='1' GROUP BY time(1s) fill(0)",
     "select": [
      [
       { "params": [ "hv_vMon" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$Channel$/" }
     ]
    }
   ]
  },
  {
   "title": "CO2 concentration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "CCS_co2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chiller temperatures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Julabo internal bath",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "chiller",
     "select": [
      [
       { "params": [ "internal_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}