FROM nodered/node-red

# Copy package.json to the WORKDIR so npm builds all
# of your added modules for Node-RED
RUN npm install --only=production \
  node-red-dashboard \ 
  node-red-node-pushbullet \
  node-red-contrib-fsm \
  node-red-contrib-hal \
  node-red-contrib-counter \
  node-red-contrib-increment \
  node-red-contrib-simple-gate \
  node-red-contrib-state \
  node-red-contrib-ui-led \
  node-red-node-serialport
  #epics \
  #node-red-contrib-epics
  
# Copy _your_ Node-RED project files into place
#COPY settings.js /data/settings.js
#COPY flows_cred.json /data/flows_cred.json
#COPY flows.json /data/flows.json

# Start the container normally
CMD ["npm", "start"]
